### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by ItsToxicGG** [Tuvqlu/Your-own-Hive#2]
config, json files, etc (not php tho) sould be in a folder called resources.

**Comment by ItsToxicGG** [comment]
ok not composer.json tho

**Comment by ItsToxicGG** [comment]
and readme.md

**Comment by ItsToxicGG** [comment]
and the phpstan and github stuff files

**Comment by Tuvqlu** [comment]
:o

**Comment by Tuvqlu** [comment]
Help me ;(

**Comment by DanteDEVS** [comment]
fixed bugs
