### ISSUE TITLE
Soon as i add to the server

### ISSUE THREAD

**Issue by SiahRBLX** [Tuvqlu/Your-own-Hive#4]
[19:18:42.535] [Server thread/CRITICAL]: Error: "Call to undefined method Tuvqlu\YourOwnHive\hive::sendTitle()" (EXCEPTION) in "plugins/YourOwnHive_dev-16.phar/src/Tuvqlu/YourOwnHive/hive" at line 24
--- Stack trace ---
  #0 pmsrc/src/event/RegisteredListener(75): Tuvqlu\YourOwnHive\hive->onJoin(object pocketmine\event\player\PlayerJoinEvent#122614)
  #1 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent#122614)
  #2 pmsrc/src/player/Player(831): pocketmine\event\Event->call()
  #3 pmsrc/src/network/mcpe/NetworkSession(714): pocketmine\player\Player->doFirstSpawn()
  #4 pmsrc/src/network/mcpe/NetworkSession(707): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
  #5 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(44): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #6 pmsrc/vendor/pocketmine/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#122609)
  #7 pmsrc/src/network/mcpe/NetworkSession(398): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#118016)
  #8 pmsrc/src/network/mcpe/NetworkSession(361): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#122609, string[2] q.)
  #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[45] c*d4...pd.C.DQg..[..l;.>-.qf...8.#S...7a.^...)
  #10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[54] .6C.J....bD.Y...,.............E...W.`.t.....z..j.=....)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#98943)
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #14 pmsrc/src/Server(1661): pocketmine\snooze\SleeperHandler->sleepUntil(double 1650827922.5483)
  #15 pmsrc/src/Server(1047): pocketmine\Server->tickProcessor()
  #16 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #17 pmsrc/src/PocketMine(327): pocketmine\server()
  #18 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by Tuvqlu** [comment]
Fixed in Dev #18!
