### ISSUE TITLE
BaseSubCommand" not found"

### ISSUE THREAD

**Issue by SiahRBLX** [Tuvqlu/Your-own-Hive#7]
[10:57:20.031] [Server thread/CRITICAL]: Error: "Class "CortexPE\Commando\BaseSubCommand" not found" (EXCEPTION) in "plugins/Your-own-Hive-2.5.0/src/Tuvqlu/YourOwnHive/hive" at line 10
--- Stack trace ---
  #0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(93): include()
  #1 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(83): BaseClassLoader->loadClass(string[23] Tuvqlu\YourOwnHive\hive)
  #2 (): BaseClassLoader->{closure}(string[23] Tuvqlu\YourOwnHive\hive)
  #3 pmsrc/src/plugin/PluginManager(146): class_exists(string[23] Tuvqlu\YourOwnHive\hive, true)
  #4 pmsrc/src/plugin/PluginManager(362): pocketmine\plugin\PluginManager->internalLoadPlugin(string[43] /home/container/plugins/Your-own-Hive-2.5.0, object DevTools\FolderPluginLoader#25756, object pocketmine\plugin\PluginDescription#25774)
  #5 pmsrc/src/Server(1007): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/, int 0)
  #6 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #7 pmsrc/src/PocketMine(327): pocketmine\server()
  #8 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Tuvqlu** [comment]
fixed in newest dev build
